### ISSUE TITLE
NameError on 'raw_input' in Python 3

### ISSUE THREAD

**Issue by mariot** [nickdibari/Get-Quote#5]
Traceback (most recent call last):
  File "GetQuote.py", line 225, in <module>
    Main()
  File "GetQuote.py", line 218, in Main
    SaveQuote(quotes_DB, quotes, author)
  File "GetQuote.py", line 57, in SaveQuote
    choice=raw_input("Please pick a quote to save (or enter done to exit): ")
NameError: name 'raw_input' is not defined

Python 3 doesn't have a 'raw_input' instruction. It uses 'input'.
If we want to maintain Python 2, should we use 'input' instead ?

In Python 2, raw_input() returns a string, and input() tries to run the input as a Python expression.
Since getting a string was almost always what you wanted, Python 3 does that with input().

In python 2.x, raw_input() returns a string and input() evaluates the input in the execution context in which it is called.
In python 3.x, input has been scrapped and the function previously known as raw_input is now input.

**Comment by mariot** [comment]
http://stackoverflow.com/questions/3800846/differences-between-input-and-raw-input

http://stackoverflow.com/questions/4915361/whats-the-difference-between-raw-input-and-input-in-python3-x

**Comment by nickdibari** [comment]
Hey sorry I missed this one I've been using python 2.7 for the purposes of testing and designing my program. I understand you've been using python 3 on windows, so there's gonna be some discrepancies. Do you think its worth it to port the whole thing to python 3.x and refactor the raw_input() to input()?

**Comment by mariot** [comment]
It would still be available for Python 3 if we use input().
Can you test on your system ?

On Thursday, 9 June 2016, nickdibari notifications@github.com wrote:

> Hey sorry I missed this one I've been using python 2.7 for the purposes
> of testing and designing my program. I understand you've been using python
> 3 on windows, so there's gonna be some discrepancies. Do you think its
> worth it to port the whole thing to python 3.x and refactor the raw_input()
> to input()?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci6.googleusercontent.com/proxy/bCqF3dGEiI6zT2HNdFTJC1PscXw_Y-xBT-zRD-v-BYspZRIU264wCkj-x0_mhwduUteV5PclIAZ0bQbi-w-YKEKzq-35T0VBn-vziJcOVtLhnd0Anu-Q4TT4pFJD37mP5VXrM1MJRpcAwks9yhU2_VLXK7y6hg=s0-d-e1-ft#https://github.com/notifications/beacon/AGAqpyuufvjB3xE6azYiqDAm-YL8uytAks5qKDr6gaJpZM4IwuId.gif

## 

Mariot Tsitoara
[image: https://]about.me/mariot.tsitoara
https://about.me/mariot.tsitoara?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

**Comment by nickdibari** [comment]
so i tried switching the interpreter from /usr/bin/python2.7 to /usr/bin/python3 and it gave me the same raw_input() error plus the other error you had fixed with the missing parens around the print statement.

here's my idea: let's switch the whole thing to python3 to be the most concurrent. i'm gonna go in and make the changes myself to ensure that it is consistent with python3 (so changing raw_input to input) and just keep it as that on github

**Comment by mariot** [comment]
Okay !
I will update my fork after you pushed your changes :)

On Friday, 10 June 2016, nickdibari notifications@github.com wrote:

> so i tried switching the interpreter from /usr/bin/python2.7 to
> /usr/bin/python3 and it gave me the same raw_input() error plus the other
> error you had fixed with the missing parens around the print statement.
> 
> here's my idea: let's switch the whole thing to python3 to be the most
> concurrent. i'm gonna go in and make the changes myself to ensure that it
> is consistent with python3 (so changing raw_input to input) and just keep
> it as that on github
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci5.googleusercontent.com/proxy/ZPTPrYIgfvrQIISsYBczCkHDXqBaAfsD6NXDhuVFCKbGTwyDi5FtnRe562KPda4QeKwf1E2n_pXRnXFl9yOlbJgV-4oBLk1cAnZshYz8gOaqNmGvEJPlJT7tckTwOpaDZFrfZbLy_v4kC-AtcWGWcTmFr-q9Vg=s0-d-e1-ft#https://github.com/notifications/beacon/AGAqp9nOSWIIsHAc1G5fIcoiZXBjGLxpks5qKbBwgaJpZM4IwuId.gif

## 

Mariot Tsitoara
[image: https://]about.me/mariot.tsitoara
https://about.me/mariot.tsitoara?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

**Comment by nickdibari** [comment]
hey dude i made the changes on my repo! test it on your system before you fork it but i ran it on my end and it checks out just fine

**Comment by mariot** [comment]
It works perfectly :+1:
